version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - apetranik
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: husky
    versions:
    - 4.3.6
  - dependency-name: react-native-screens
    versions:
    - 2.16.1
  - dependency-name: core-js
    versions:
    - 3.8.1
