version: 2
jobs:
  build:
    working_directory: ~/gladeo
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@latest
    - run:
        name: install-yarn
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: install-dependencies
        command: yarn install
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - run:
        name: Install JUnit coverage reporter
        command: yarn add --dev jest-junit
    - run:
        name: Run tests with JUnit as reporter
        command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
        environment:
          JEST_JUNIT_OUTPUT_DIR: "reports/coverage"
    - run:
        name: JavaScript Linter
        # yarn here makes sure we are using the local jest binary
        command: yarn lint -- --format junit -o reports/linter
    - store_artifacts:
        path: reports
    - store_test_results:
        path: reports
workflows:
  version: 2
  workflow:
    jobs:
    - build